// Code generated by protoc-gen-go-tcp. DO NOT EDIT.
// versions:
// - protoc-gen-go-tcp v2.8.3
// - protoc            v3.6.1
// source: metadata/metadata.proto

package metadata

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
import (
	"context"
	"runtime/debug"

	"github.com/yola1107/kratos/v2/log"
	"github.com/yola1107/kratos/v2/transport/tcp"

	"google.golang.org/protobuf/proto"
)

var (
	ins *Loop
)

type Loop struct {
	jobs   chan func()
	toggle chan byte
}

func RecoverFromError(cb func()) {
	if e := recover(); e != nil {
		log.Error("Recover => %s:%s\n", e, debug.Stack())
		if cb != nil {
			cb()
		}
	}
}
func (lp *Loop) Start() {
	log.Info("loop routine start.")
	go func() {
		defer RecoverFromError(func() {
			lp.Start()
		})
		for {
			select {
			case <-lp.toggle:
				log.Info("Loop routine stop.")
				return
			case job := <-lp.jobs:
				job()
			}
		}
	}()
}
func (lp *Loop) Stop() {
	go func() {
		lp.toggle <- 1
	}()
}
func Stop() { ins.Stop() }
func (lp *Loop) Jobs() int {
	return len(lp.jobs)
}
func Jobs() int { return ins.Jobs() }
func (lp *Loop) Post(job func()) {
	go func() {
		lp.jobs <- job
	}()
}
func Post(job func()) { ins.Post(job) }
func (lp *Loop) PostAndWait(job func() interface{}) interface{} {
	ch := make(chan interface{})
	go func() {
		lp.jobs <- func() {
			ch <- job()
		}
	}()
	return <-ch
}
func PostAndWait(job func() interface{}) interface{} { return ins.PostAndWait(job) }

// MetadataTcpServer is the server API for Metadata service.
type MetadataTCPServer interface {
	SetCometChan(cl *tcp.ChanList, cs *tcp.Server)
	IsLoopFunc(f string) (isLoop bool)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesReply, error)
	GetServiceDesc(context.Context, *GetServiceDescRequest) (*GetServiceDescReply, error)
}

func RegisterMetadataTCPServer(s *tcp.Server, srv MetadataTCPServer) {
	chanList := s.RegisterService(&Metadata_TCP_ServiceDesc, srv)
	srv.SetCometChan(chanList, s)
	ins = &Loop{jobs: make(chan func(), 10000), toggle: make(chan byte)}
	ins.Start()
}

func _Metadata_ListServices_TCP_Handler(srv interface{}, ctx context.Context, data []byte, interceptor tcp.UnaryServerInterceptor) ([]byte, error) {
	in := new(ListServicesRequest)
	if err := proto.Unmarshal(data, in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		out, err := srv.(MetadataTCPServer).ListServices(ctx, in)
		data, _ := proto.Marshal(out)
		return data, err
	}
	info := &tcp.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kratos.api.Metadata/ListServices",
	}
	handler := func(ctx context.Context, req interface{}) ([]byte, error) {
		out := new(ListServicesReply)
		var err error
		if srv.(MetadataTCPServer).IsLoopFunc("ListServices") {
			rspChan := make(chan *ListServicesReply)
			errChan := make(chan error)
			ins.Post(func() {
				resp, err := srv.(MetadataTCPServer).ListServices(ctx, req.(*ListServicesRequest))
				rspChan <- resp
				errChan <- err
			})
			out = <-rspChan
			err = <-errChan
		} else {
			out, err = srv.(MetadataTCPServer).ListServices(ctx, req.(*ListServicesRequest))
		}
		if out != nil {
			data, _ := proto.Marshal(out)
			return data, err
		}
		return nil, err
	}
	return interceptor(ctx, in, info, handler)
}

func _Metadata_GetServiceDesc_TCP_Handler(srv interface{}, ctx context.Context, data []byte, interceptor tcp.UnaryServerInterceptor) ([]byte, error) {
	in := new(GetServiceDescRequest)
	if err := proto.Unmarshal(data, in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		out, err := srv.(MetadataTCPServer).GetServiceDesc(ctx, in)
		data, _ := proto.Marshal(out)
		return data, err
	}
	info := &tcp.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kratos.api.Metadata/GetServiceDesc",
	}
	handler := func(ctx context.Context, req interface{}) ([]byte, error) {
		out := new(GetServiceDescReply)
		var err error
		if srv.(MetadataTCPServer).IsLoopFunc("GetServiceDesc") {
			rspChan := make(chan *GetServiceDescReply)
			errChan := make(chan error)
			ins.Post(func() {
				resp, err := srv.(MetadataTCPServer).GetServiceDesc(ctx, req.(*GetServiceDescRequest))
				rspChan <- resp
				errChan <- err
			})
			out = <-rspChan
			err = <-errChan
		} else {
			out, err = srv.(MetadataTCPServer).GetServiceDesc(ctx, req.(*GetServiceDescRequest))
		}
		if out != nil {
			data, _ := proto.Marshal(out)
			return data, err
		}
		return nil, err
	}
	return interceptor(ctx, in, info, handler)
}

var Metadata_TCP_ServiceDesc = tcp.ServiceDesc{
	ServiceName: "kratos.api.Metadata",
	HandlerType: (*MetadataTCPServer)(nil),
	Methods: []tcp.MethodDesc{
		{
			MethodName: "ListServices",
			Handler:    _Metadata_ListServices_TCP_Handler,
			Ops:        1001,
		},
		{
			MethodName: "GetServiceDesc",
			Handler:    _Metadata_GetServiceDesc_TCP_Handler,
			Ops:        1003,
		},
	},
}
